# Generated by Django 4.2.7 on 2023-11-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='uploaded_by',
        ),
    ]
